// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package podcastaddict

import (
	"database/sql"
)

type AdCampaign struct {
	ID                          int64
	Type                        sql.NullString
	PodcastID                   int64
	ServerID                    int64
	Language                    string
	Enabled                     interface{}
	PaidAdvertisement           interface{}
	CategoryID                  int64
	Position                    int64
	ArtworkID                   int64
	FeatureInPopularSearchTerms interface{}
	SearchTerms                 sql.NullString
}

type Alarm struct {
	ID        int64
	Time      int64
	Enabled   int64
	Frequency int64
	Name      sql.NullString
	Type      int64
	Entityid  int64
	Volume    int64
}

type AndroidMetadatum struct {
	Locale sql.NullString
}

type Bitmap struct {
	ID           int64
	Url          string
	IsAsset      int64
	IsDownloaded int64
	LocalFile    sql.NullString
	Md5          sql.NullString
}

type BlockingService struct {
	ID      int64
	Type    int64
	Pattern string
}

type Chapter struct {
	ID             int64
	Podcastid      int64
	Episodeid      int64
	Start          int64
	Name           sql.NullString
	Description    sql.NullString
	Url            sql.NullString
	Artworkid      sql.NullInt64
	Custombookmark interface{}
	Diaporamaflag  interface{}
	Updatedate     sql.NullInt64
	Ismuted        sql.NullInt64
	Ismusic        interface{}
	Loopmode       interface{}
}

type Comment struct {
	ID          int64
	EpisodeID   int64
	PodcastID   int64
	Title       sql.NullString
	Creator     string
	Link        string
	Pubdate     int64
	Guid        string
	Description sql.NullString
	Content     sql.NullString
	NewStatus   int64
}

type ContentPolicyViolation struct {
	ID   int64
	Name string
	Url  sql.NullString
}

type CuratedList struct {
	ID          int64
	ServerID    int64
	Type        int64
	Language    string
	Enabled     interface{}
	Position    int64
	Name        string
	Description string
	BannerID    string
	HeaderID    sql.NullString
}

type Episode struct {
	ID                      int64
	Name                    string
	PodcastID               int64
	Guid                    string
	Url                     sql.NullString
	Comments                sql.NullString
	PublicationDate         int64
	Creator                 sql.NullString
	Categories              sql.NullString
	Description             sql.NullString
	ShortDescription        sql.NullString
	Content                 sql.NullString
	ThumbnailUrl            sql.NullString
	CommentRss              sql.NullString
	DownloadUrl             sql.NullString
	Type                    sql.NullString
	Duration                sql.NullString
	Size                    int64
	Rating                  float64
	DownloadedStatus        string
	Favorite                int64
	SeenStatus              int64
	DownloadedDate          sql.NullInt64
	NewStatus               int64
	PlayingStatus           int64
	PositionToResume        sql.NullInt64
	DeletedStatus           int64
	LocalFileName           sql.NullString
	ThumbnailID             sql.NullInt64
	CommentsLastModified    int64
	CommentsEtag            string
	DurationMs              int64
	Flattr                  sql.NullString
	IsVirtual               sql.NullInt64
	IsArtworkExtracted      sql.NullInt64
	Virtualpodcastname      sql.NullString
	Normalizedtype          sql.NullInt64
	Hasbeenflattred         interface{}
	Playbackdate            int64
	DownloadErrorMsg        sql.NullString
	MediaExtractedArtworkID sql.NullInt64
	ChaptersExtracted       interface{}
	ServerID                sql.NullInt64
	AutomaticallyShared     interface{}
	DownloadedStatusInt     interface{}
	DonationUrl             sql.NullString
	Explicit                interface{}
	Itunestype              sql.NullInt64
	Seasonnb                sql.NullInt64
	Episodenb               sql.NullInt64
	TranscriptUrl           sql.NullString
	ChaptersUrl             sql.NullString
	Seasonname              sql.NullString
	Thumbsrating            interface{}
	AlternateUrls           sql.NullString
	RssfeedDurationMs       int64
	ChapterOrigin           sql.NullInt64
}

type EpisodeSearchResult struct {
	ID                 int64
	SearchType         int64
	CategoryID         sql.NullInt64
	Podcastid          sql.NullInt64
	Podcastserverid    int64
	Podcastfeedurl     string
	Podcastname        string
	Author             sql.NullString
	Language           string
	PodcastThumbnailID sql.NullInt64
	Itunesid           sql.NullString
	Episodeid          sql.NullInt64
	Episodeserverid    int64
	Episodeurl         string
	Episodename        string
	Description        string
	EpisodeThumbnailID sql.NullInt64
	Publicationdate    int64
	Duration           sql.NullInt64
	Type               string
	Score              int64
}

type Genre struct {
	ID   int64
	Name string
}

type GenreRelation struct {
	ID      int64
	GenreID int64
	RadioID int64
}

type Iha struct {
	ID                 int64
	ServerID           int64
	Format             interface{}
	Url                string
	Enabled            interface{}
	ArtworkPortraitID  int64
	ArtworkLandscapeID int64
}

type Location struct {
	ID   int64
	Name string
	Data sql.NullString
}

type LocationRelation struct {
	ID         int64
	LocationID int64
	PodcastID  int64
	EpisodeID  int64
}

type OrderedList struct {
	Rank   int64
	ID     int64
	Type   int64
	Filter sql.NullInt64
}

type Person struct {
	ID        int64
	Name      string
	PictureID int64
	BioUrl    sql.NullString
}

type PersonRelation struct {
	ID        int64
	PersonID  int64
	PodcastID int64
	EpisodeID int64
	Role      sql.NullString
	Category  sql.NullString
}

type Podcast struct {
	ID                            int64
	Name                          string
	TeamID                        int64
	Category                      sql.NullString
	Type                          string
	SubscribedStatus              int64
	Version                       int64
	Homepage                      sql.NullString
	LatestPublicationDate         int64
	FeedUrl                       string
	Favorite                      sql.NullInt64
	Rating                        float64
	UpdateStatus                  int64
	UpdateDate                    sql.NullInt64
	ThumbnailID                   sql.NullInt64
	StoreUrl                      sql.NullString
	LastModified                  int64
	Etag                          string
	InitializedStatus             int64
	Charset                       sql.NullString
	LastUpdateFailure             int64
	Flattr                        sql.NullString
	IsVirtual                     sql.NullInt64
	IsComplete                    sql.NullInt64
	Language                      sql.NullString
	Author                        sql.NullString
	Description                   sql.NullString
	CustomName                    sql.NullString
	Priority                      int64
	AcceptAudio                   int64
	AcceptVideo                   int64
	AcceptText                    int64
	FilterIncludedKeywords        sql.NullString
	FilterExcludedKeywords        sql.NullString
	UpdateErrorMessage            sql.NullString
	Authentication                sql.NullInt64
	Login                         sql.NullString
	Password                      sql.NullString
	Automaticrefresh              sql.NullInt64
	Foldername                    sql.NullString
	Private                       interface{}
	Itunesid                      sql.NullString
	Subscribers                   sql.NullInt64
	Averageduration               sql.NullInt64
	Frequency                     sql.NullInt64
	Episodesnb                    sql.NullInt64
	Explicit                      interface{}
	Itunestype                    sql.NullInt64
	Reviews                       sql.NullInt64
	Position                      sql.NullInt64
	ServerID                      sql.NullInt64
	Muted                         interface{}
	HubUrl                        sql.NullString
	TopicUrl                      sql.NullString
	Websubsubscribed              interface{}
	FilterChapterExcludedKeywords sql.NullString
	LastPlayedEpisodeDate         sql.NullInt64
	Guid                          sql.NullString
	Livestreamid                  int64
	Livestreamstart               int64
	Livestreamend                 int64
	Livestreamguid                sql.NullString
	Livestreamstatus              interface{}
	NextEpisodeForecastDate       int64
}

type PopularSearchTerm struct {
	ID        int64
	Languages string
	Keywords  string
}

type RadioSearchResult struct {
	ID          int64
	Url         string
	Name        string
	Country     sql.NullString
	Language    sql.NullString
	Genre       sql.NullString
	Description sql.NullString
	ThumbnailID sql.NullInt64
	Quality     sql.NullInt64
	Tuneinid    sql.NullString
	Serverid    sql.NullInt64
	Episodeid   sql.NullInt64
	Countrycode sql.NullString
	Subscribers sql.NullInt64
	Type        int64
}

type Relatedpodcast struct {
	ID        int64
	Relation  int64
	Url       string
	SimilarID int64
	Position  int64
	Score     int64
}

type Review struct {
	ID             int64
	Serverid       int64
	PodcastID      int64
	Username       string
	Date           int64
	Ismyreview     sql.NullInt64
	Hasbeenflagged sql.NullInt64
	Rating         int64
	Comment        sql.NullString
}

type ServerAction struct {
	ID        int64
	Type      int64
	Entity    sql.NullInt64
	Entityid  int64
	Value     sql.NullInt64
	Timestamp int64
}

type Social struct {
	ID        int64
	Podcastid int64
	Episodeid int64
	Priority  int64
	Platform  string
	Accountid string
	Url       string
	Date      sql.NullInt64
	Json      sql.NullString
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}

type SqliteStat1 struct {
	Tbl  interface{}
	Idx  interface{}
	Stat interface{}
}

type Statistic struct {
	ID             int64
	Entitytype     int64
	Entityid       int64
	Entitystringid sql.NullString
	Type           int64
	Value          sql.NullInt64
	Timestamp      int64
}

type SupportedLanguage struct {
	ID        int64
	LongName  string
	ShortName string
}

type Tag struct {
	ID               int64
	Name             string
	RefreshFrequency int64
	RefreshTime      int64
}

type TagRelation struct {
	ID        int64
	TagID     int64
	PodcastID int64
}

type Team struct {
	ID                        int64
	Name                      string
	HomePage                  string
	Version                   int64
	BannerID                  int64
	ThumbnailID               sql.NullInt64
	StoreUrl                  sql.NullString
	Language                  string
	LastModificationTimestamp int64
	Priority                  int64
}

type TimestampList struct {
	ID        int64
	ItemID    int64
	Timestamp int64
	Type      int64
}

type Topic struct {
	ID       int64
	Name     string
	Keywords string
	Nbdays   int64
	Position int64
}
