// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package podcastaddict

import (
	"context"
	"database/sql"
)

const getAllPodcasts = `-- name: GetAllPodcasts :many
SELECT _id AS id, name AS title, feed_url 
FROM podcasts 
WHERE subscribed_status IS TRUE
ORDER BY name ASC
`

type GetAllPodcastsRow struct {
	ID      int64
	Title   string
	FeedUrl string
}

// Get all subscribed podcasts with their basic information
func (q *Queries) GetAllPodcasts(ctx context.Context) ([]GetAllPodcastsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPodcasts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPodcastsRow
	for rows.Next() {
		var i GetAllPodcastsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.FeedUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPodcastStats = `-- name: GetPodcastStats :many
SELECT p.name,
    p.author,
    p.feed_url,
    p.frequency,
    p.averageDuration AS average_duration,
    COALESCE(e.unplayed_count, 0) AS unplayed_episodes,
    p.priority
FROM podcasts p
    LEFT JOIN (
        SELECT podcast_id,
            COUNT(*) AS unplayed_count
        FROM episodes
        WHERE seen_status = 0 -- 0 = FALSE (not seen/unplayed)
        GROUP BY podcast_id
    ) e ON p._id = e.podcast_id
WHERE p.subscribed_status IS TRUE
ORDER BY p.priority DESC,
    p.name ASC
`

type GetPodcastStatsRow struct {
	Name             string
	Author           sql.NullString
	FeedUrl          string
	Frequency        sql.NullInt64
	AverageDuration  sql.NullInt64
	UnplayedEpisodes int64
	Priority         int64
}

// Retrieve podcast statistics including unlistened episode count
func (q *Queries) GetPodcastStats(ctx context.Context) ([]GetPodcastStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPodcastStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPodcastStatsRow
	for rows.Next() {
		var i GetPodcastStatsRow
		if err := rows.Scan(
			&i.Name,
			&i.Author,
			&i.FeedUrl,
			&i.Frequency,
			&i.AverageDuration,
			&i.UnplayedEpisodes,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPodcastStatsByTag = `-- name: GetPodcastStatsByTag :many
SELECT p.name,
    p.author,
    p.feed_url,
    p.frequency,
    p.averageDuration AS average_duration,
    COALESCE(e.unplayed_count, 0) AS unplayed_episodes,
    p.priority
FROM podcasts p
    LEFT JOIN (
        SELECT podcast_id,
            COUNT(*) AS unplayed_count
        FROM episodes
        WHERE seen_status = 0 -- 0 = FALSE (not seen/unplayed)
        GROUP BY podcast_id
    ) e ON p._id = e.podcast_id
    INNER JOIN tag_relation tr ON p._id = tr.podcast_id
    INNER JOIN tags t ON tr.tag_id = t._id
WHERE p.subscribed_status IS TRUE
    AND t.name = ?
ORDER BY p.priority DESC,
    p.name ASC
`

type GetPodcastStatsByTagRow struct {
	Name             string
	Author           sql.NullString
	FeedUrl          string
	Frequency        sql.NullInt64
	AverageDuration  sql.NullInt64
	UnplayedEpisodes int64
	Priority         int64
}

// Retrieve podcast statistics filtered by tag
func (q *Queries) GetPodcastStatsByTag(ctx context.Context, name string) ([]GetPodcastStatsByTagRow, error) {
	rows, err := q.db.QueryContext(ctx, getPodcastStatsByTag, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPodcastStatsByTagRow
	for rows.Next() {
		var i GetPodcastStatsByTagRow
		if err := rows.Scan(
			&i.Name,
			&i.Author,
			&i.FeedUrl,
			&i.Frequency,
			&i.AverageDuration,
			&i.UnplayedEpisodes,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTags = `-- name: GetTags :many
SELECT DISTINCT t.name
FROM tags t
INNER JOIN tag_relation tr ON t._id = tr.tag_id
INNER JOIN podcasts p ON tr.podcast_id = p._id
WHERE p.subscribed_status IS TRUE
ORDER BY t.name ASC
`

// Get all tags from subscribed podcasts
func (q *Queries) GetTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriority = `-- name: UpdatePriority :exec
UPDATE podcasts
SET priority = ?
WHERE feed_url = ?
`

type UpdatePriorityParams struct {
	Priority int64
	FeedUrl  string
}

// Update the priority of a podcast by its feed URL
func (q *Queries) UpdatePriority(ctx context.Context, arg UpdatePriorityParams) error {
	_, err := q.db.ExecContext(ctx, updatePriority, arg.Priority, arg.FeedUrl)
	return err
}
