// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package podcastaddict

import (
	"context"
	"database/sql"
)

const getCategories = `-- name: GetCategories :many
SELECT DISTINCT p.category
FROM podcasts p
WHERE p.subscribed_status IS TRUE
    AND p.category IS NOT NULL
    AND p.category != ''
ORDER BY p.category ASC
`

// Get all unique categories from subscribed podcasts
func (q *Queries) GetCategories(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var category sql.NullString
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPodcastStats = `-- name: GetPodcastStats :many
SELECT p.name,
    p.author,
    p.feed_url,
    p.frequency,
    p.averageDuration AS average_duration,
    COALESCE(e.unplayed_count, 0) AS unplayed_episodes,
    p.priority
FROM podcasts p
    LEFT JOIN (
        SELECT podcast_id,
            COUNT(*) AS unplayed_count
        FROM episodes
        WHERE seen_status = 0 -- 0 = FALSE (not seen/unplayed)
        GROUP BY podcast_id
    ) e ON p._id = e.podcast_id
WHERE p.subscribed_status IS TRUE
ORDER BY p.priority DESC,
    p.name ASC
`

type GetPodcastStatsRow struct {
	Name             string
	Author           sql.NullString
	FeedUrl          string
	Frequency        sql.NullInt64
	AverageDuration  sql.NullInt64
	UnplayedEpisodes int64
	Priority         int64
}

// Retrieve podcast statistics including unlistened episode count
func (q *Queries) GetPodcastStats(ctx context.Context) ([]GetPodcastStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPodcastStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPodcastStatsRow
	for rows.Next() {
		var i GetPodcastStatsRow
		if err := rows.Scan(
			&i.Name,
			&i.Author,
			&i.FeedUrl,
			&i.Frequency,
			&i.AverageDuration,
			&i.UnplayedEpisodes,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPodcastStatsByCategory = `-- name: GetPodcastStatsByCategory :many
SELECT p.name,
    p.author,
    p.feed_url,
    p.frequency,
    p.averageDuration AS average_duration,
    COALESCE(e.unplayed_count, 0) AS unplayed_episodes,
    p.priority
FROM podcasts p
    LEFT JOIN (
        SELECT podcast_id,
            COUNT(*) AS unplayed_count
        FROM episodes
        WHERE seen_status = 0 -- 0 = FALSE (not seen/unplayed)
        GROUP BY podcast_id
    ) e ON p._id = e.podcast_id
WHERE p.subscribed_status IS TRUE
    AND p.category = ?
ORDER BY p.priority DESC,
    p.name ASC
`

type GetPodcastStatsByCategoryRow struct {
	Name             string
	Author           sql.NullString
	FeedUrl          string
	Frequency        sql.NullInt64
	AverageDuration  sql.NullInt64
	UnplayedEpisodes int64
	Priority         int64
}

// Retrieve podcast statistics filtered by category
func (q *Queries) GetPodcastStatsByCategory(ctx context.Context, category sql.NullString) ([]GetPodcastStatsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getPodcastStatsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPodcastStatsByCategoryRow
	for rows.Next() {
		var i GetPodcastStatsByCategoryRow
		if err := rows.Scan(
			&i.Name,
			&i.Author,
			&i.FeedUrl,
			&i.Frequency,
			&i.AverageDuration,
			&i.UnplayedEpisodes,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriority = `-- name: UpdatePriority :exec
UPDATE podcasts
SET priority = ?
WHERE feed_url = ?
`

type UpdatePriorityParams struct {
	Priority int64
	FeedUrl  string
}

// Update the priority of a podcast by its feed URL
func (q *Queries) UpdatePriority(ctx context.Context, arg UpdatePriorityParams) error {
	_, err := q.db.ExecContext(ctx, updatePriority, arg.Priority, arg.FeedUrl)
	return err
}
